import { IEducationalEstablishments } from "@/shared/lib/types";

export const educationalEstablishmentsList: IEducationalEstablishments[] = [
  {
    id: 1,
    name: "name educationalEstablishments",
    type: "educationalEstablishments",
    transliterationName: "transliteration educationalEstablishments",
    icon: "/",
    previewDesc: "previewDesc educationalEstablishments",
    photos: [""],
    previewPhoto: "/",
    description: "desc educationalEstablishments", // редактор
    fullNameLocation: "Yaroslavl",
    location: [1, 2],
    city: "city educationalEstablishments",
    tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
    createdAt: new Date(),
    dateOfBirth: new Date(),
    contacts: [{ id: 1, name: "Vladimir", contact: "7-777-777-777", type: "phone" }],
    site: "www.site.ru",
    specialization: "specialization educationalEstablishments",
    staff: [
      {
        id: 1,
        photo: "/",
        name: "Иван",
        surname: "Абрамович",
        middleName: "Юрьевич",
        position: "Основатель СЕВЕРМАШ",
        contactStaff: { id: 1, name: "Vladimir", contact: "7-777-777-777", type: "phone" },
      },
    ],
    advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
    phone: "7-777-777-77",
    // ----
    similarEducationalEstablishments: [
      {
        id: 1,
        name: "name educationalEstablishments",
        type: "educationalEstablishments",
        transliterationName: "transliteration educationalEstablishments",
        icon: "/",
        previewDesc: "previewDesc educationalEstablishments",
        photos: [""],
        previewPhoto: "/",
        description: "desc educationalEstablishments", // редактор
        fullNameLocation: "Yaroslavl",
        location: [1, 2],
        city: "city educationalEstablishments",
        tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
        createdAt: new Date(),
        dateOfBirth: new Date(),
        contacts: [{ id: 1, name: "Vladimir", contact: "7-777-777-777", type: "phone" }],
        site: "www.site.ru",
        specialization: "specialization educationalEstablishments",
        staff: [
          {
            id: 1,
            photo: "/",
            name: "Иван",
            surname: "Абрамович",
            middleName: "Юрьевич",
            position: "Основатель СЕВЕРМАШ",
            contactStaff: { id: 1, name: "Vladimir", contact: "7-777-777-777", type: "phone" },
          },
        ],
        advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
        phone: "7-777-777-77",
        // ----
        similarEducationalEstablishments: [],
        otherEducationalEstablishments: [],
        professions: [],
        enterprises: [],
        internshipsAndInternships: [],
        vacancy: [],
      },
    ],
    otherEducationalEstablishments: [
      {
        id: 1,
        name: "name educationalEstablishments",
        type: "educationalEstablishments",
        transliterationName: "transliteration educationalEstablishments",
        icon: "/",
        previewDesc: "previewDesc educationalEstablishments",
        photos: [""],
        previewPhoto: "/",
        description: "desc educationalEstablishments", // редактор
        fullNameLocation: "Yaroslavl",
        location: [1, 2],
        city: "city educationalEstablishments",
        tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
        createdAt: new Date(),
        dateOfBirth: new Date(),
        contacts: [{ id: 1, name: "Vladimir", contact: "7-777-777-777", type: "phone" }],
        site: "www.site.ru",
        specialization: "specialization educationalEstablishments",
        staff: [
          {
            id: 1,
            photo: "/",
            name: "Иван",
            surname: "Абрамович",
            middleName: "Юрьевич",
            position: "Основатель СЕВЕРМАШ",
            contactStaff: { id: 1, name: "Vladimir", contact: "7-777-777-777", type: "phone" },
          },
        ],
        advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
        phone: "7-777-777-77",
        // ----
        similarEducationalEstablishments: [],
        otherEducationalEstablishments: [],
        professions: [],
        enterprises: [],
        internshipsAndInternships: [],
        vacancy: [],
      },
    ],
    professions: [],
    enterprises: [],
    internshipsAndInternships: [],
    vacancy: [],
  },
];
