import { IInternshipsAndPractices } from "@/shared/lib/types";

export const internshipsAndPracticesList: IInternshipsAndPractices[] = [
  {
    id: 1,
    type: "internshipsAndPractices",
    typeInternship: "practice",
    name: "name internshipsAndPractices",
    transliterationName: "transliterationName internshipsAndPractices",
    enterprise: {
      id: 1,
      name: "name enterprise",
      type: "enterprise",
      transliterationName: "enterprise_transliteration",
      profession: {
        id: 1,
        type: "profession",
        name: "name profession",
        transliterationName: "transiteration_name_profession",
        icon: "/",
        startSalary: 50_000,
        endSalary: 250_000,
        averageSalary: 150_000,
        salaryCurrency: "rub",
        previewDesc: "previewDesc profession",
        description: "desc profession", // редактор
        photos: [""],
        previewPhoto: "/",
        subcategories: [], // IProfession[]
        knowledge: [""], // можно вставить редактор описние или массив строк
        tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
        DateOfBirth: new Date(),
        // ----
        similarProfessions: [],
        otherProfessions: [],
        educationalEstablishments: [],
        enterprises: [],
        internshipsAndInternships: [],
        vacancy: [],
      }, // IProfession
      icon: "/",
      startSalary: 50_000,
      endSalary: 250_000,
      previewDesc: "description enterprise",
      photos: [""],
      previewPhoto: "/",
      description: "desc full enterprise", // редактор
      fullNameLocation: "Yaroslavl",
      location: [1, 2],
      knowledge: [""], // можно вставить редактор описние или массив строк
      tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
      createdAt: new Date(),
      DateOfBirth: new Date(),
      contacts: [{ name: "Vladimir", contact: "Zenovsky" }],
      city: "city enterprise",
      site: "site enterprise",
      sizeCompany: [10],
      specialization: "specialization enterprise",
      staff: [
        {
          id: 1,
          photo: "/",
          name: "Иван",
          surname: "Абрамович",
          middleName: "Юрьевич",
          position: "Основатель СЕВЕРМАШ",
          contact: { name: "Иван Юрьевич", contact: "7-777-777-777" },
        },
      ],
      advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
      phone: "7-777-777-77",
      // ----
      similarEnterprises: [],
      otherEnterprises: [],
      educationalEstablishments: [],
      professions: [],
      internshipsAndInternships: [],
      vacancy: [],
    },
    profession: {
      id: 1,
      type: "profession",
      name: "name profession",
      transliterationName: "transiteration_name_profession",
      icon: "/",
      startSalary: 50_000,
      endSalary: 250_000,
      averageSalary: 150_000,
      salaryCurrency: "rub",
      previewDesc: "previewDesc profession",
      description: "desc profession", // редактор
      photos: [""],
      previewPhoto: "/",
      subcategories: [], // IProfession[]
      knowledge: [""], // можно вставить редактор описние или массив строк
      tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
      DateOfBirth: new Date(),
      // ----
      similarProfessions: [],
      otherProfessions: [],
      educationalEstablishments: [],
      enterprises: [],
      internshipsAndInternships: [],
      vacancy: [],
    },
    icon: "/",
    startSalary: 50_000,
    endSalary: 250_000,
    salaryPeriod: "hour",
    salaryCurrency: "rub",
    previewDesc: "desc preview internshipsAndPractices",
    photos: [""],
    previewPhoto: "/",
    description: "desc internshipsAndPractices", // редактор
    fullNameLocation: "yaroslavl",
    location: [1, 2],
    knowledge: [""], // можно вставить редактор описние или массив строк
    tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
    createdAt: new Date(),
    contacts: [{ name: "Vladimir", contact: "Zenovsky" }],
    city: "Yaroslavl",
    sizeInternshipsOrPractice: [10],
    specialization: "specialization internshipsAndPractices",
    staff: [
      {
        id: 1,
        photo: "/",
        name: "Иван",
        surname: "Абрамович",
        middleName: "Юрьевич",
        position: "Основатель СЕВЕРМАШ",
        contact: { name: "Иван Юрьевич", contact: "7-777-777-777" },
      },
    ],
    advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
    phone: "7-777-777-77",
    // ----
    similarInternshipsAndPractices: [
      {
        id: 1,
        type: "internshipsAndPractices",
        typeInternship: "practice",
        name: "name internshipsAndPractices",
        transliterationName: "transliterationName internshipsAndPractices",
        enterprise: {
          id: 1,
          name: "name enterprise",
          type: "enterprise",
          transliterationName: "enterprise_transliteration",
          profession: {
            id: 1,
            type: "profession",
            name: "name profession",
            transliterationName: "transiteration_name_profession",
            icon: "/",
            startSalary: 50_000,
            endSalary: 250_000,
            averageSalary: 150_000,
            salaryCurrency: "rub",
            previewDesc: "previewDesc profession",
            description: "desc profession", // редактор
            photos: [""],
            previewPhoto: "/",
            subcategories: [], // IProfession[]
            knowledge: [""], // можно вставить редактор описние или массив строк
            tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
            DateOfBirth: new Date(),
            // ----
            similarProfessions: [],
            otherProfessions: [],
            educationalEstablishments: [],
            enterprises: [],
            internshipsAndInternships: [],
            vacancy: [],
          }, // IProfession
          icon: "/",
          startSalary: 50_000,
          endSalary: 250_000,
          previewDesc: "description enterprise",
          photos: [""],
          previewPhoto: "/",
          description: "desc full enterprise", // редактор
          fullNameLocation: "Yaroslavl",
          location: [1, 2],
          knowledge: [""], // можно вставить редактор описние или массив строк
          tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
          createdAt: new Date(),
          DateOfBirth: new Date(),
          contacts: [{ name: "Vladimir", contact: "Zenovsky" }],
          city: "city enterprise",
          site: "site enterprise",
          sizeCompany: [10],
          specialization: "specialization enterprise",
          staff: [
            {
              id: 1,
              photo: "/",
              name: "Иван",
              surname: "Абрамович",
              middleName: "Юрьевич",
              position: "Основатель СЕВЕРМАШ",
              contact: { name: "Иван Юрьевич", contact: "7-777-777-777" },
            },
          ],
          advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
          phone: "7-777-777-77",
          // ----
          similarEnterprises: [],
          otherEnterprises: [],
          educationalEstablishments: [],
          professions: [],
          internshipsAndInternships: [],
          vacancy: [],
        },
        profession: {
          id: 1,
          type: "profession",
          name: "name profession",
          transliterationName: "transiteration_name_profession",
          icon: "/",
          startSalary: 50_000,
          endSalary: 250_000,
          averageSalary: 150_000,
          salaryCurrency: "rub",
          previewDesc: "previewDesc profession",
          description: "desc profession", // редактор
          photos: [""],
          previewPhoto: "/",
          subcategories: [], // IProfession[]
          knowledge: [""], // можно вставить редактор описние или массив строк
          tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
          DateOfBirth: new Date(),
          // ----
          similarProfessions: [],
          otherProfessions: [],
          educationalEstablishments: [],
          enterprises: [],
          internshipsAndInternships: [],
          vacancy: [],
        },
        icon: "/",
        startSalary: 50_000,
        endSalary: 250_000,
        salaryPeriod: "hour",
        salaryCurrency: "rub",
        previewDesc: "desc preview internshipsAndPractices",
        photos: [""],
        previewPhoto: "/",
        description: "desc internshipsAndPractices", // редактор
        fullNameLocation: "yaroslavl",
        location: [1, 2],
        knowledge: [""], // можно вставить редактор описние или массив строк
        tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
        createdAt: new Date(),
        contacts: [{ name: "Vladimir", contact: "Zenovsky" }],
        city: "Yaroslavl",
        sizeInternshipsOrPractice: [10],
        specialization: "specialization internshipsAndPractices",
        staff: [
          {
            id: 1,
            photo: "/",
            name: "Иван",
            surname: "Абрамович",
            middleName: "Юрьевич",
            position: "Основатель СЕВЕРМАШ",
            contact: { name: "Иван Юрьевич", contact: "7-777-777-777" },
          },
        ],
        advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
        phone: "7-777-777-77",
        // ----
        similarInternshipsAndPractices: [],
        otherInternshipsAndPractices: [],
        educationalEstablishments: [],
        enterprises: [],
        professions: [],
        vacancy: [],
      },
    ],
    otherInternshipsAndPractices: [
      {
        id: 1,
        type: "internshipsAndPractices",
        typeInternship: "practice",
        name: "name internshipsAndPractices",
        transliterationName: "transliterationName internshipsAndPractices",
        enterprise: {
          id: 1,
          name: "name enterprise",
          type: "enterprise",
          transliterationName: "enterprise_transliteration",
          profession: {
            id: 1,
            type: "profession",
            name: "name profession",
            transliterationName: "transiteration_name_profession",
            icon: "/",
            startSalary: 50_000,
            endSalary: 250_000,
            averageSalary: 150_000,
            salaryCurrency: "rub",
            previewDesc: "previewDesc profession",
            description: "desc profession", // редактор
            photos: [""],
            previewPhoto: "/",
            subcategories: [], // IProfession[]
            knowledge: [""], // можно вставить редактор описние или массив строк
            tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
            DateOfBirth: new Date(),
            // ----
            similarProfessions: [],
            otherProfessions: [],
            educationalEstablishments: [],
            enterprises: [],
            internshipsAndInternships: [],
            vacancy: [],
          }, // IProfession
          icon: "/",
          startSalary: 50_000,
          endSalary: 250_000,
          previewDesc: "description enterprise",
          photos: [""],
          previewPhoto: "/",
          description: "desc full enterprise", // редактор
          fullNameLocation: "Yaroslavl",
          location: [1, 2],
          knowledge: [""], // можно вставить редактор описние или массив строк
          tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
          createdAt: new Date(),
          DateOfBirth: new Date(),
          contacts: [{ name: "Vladimir", contact: "Zenovsky" }],
          city: "city enterprise",
          site: "site enterprise",
          sizeCompany: [10],
          specialization: "specialization enterprise",
          staff: [
            {
              id: 1,
              photo: "/",
              name: "Иван",
              surname: "Абрамович",
              middleName: "Юрьевич",
              position: "Основатель СЕВЕРМАШ",
              contact: { name: "Иван Юрьевич", contact: "7-777-777-777" },
            },
          ],
          advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
          phone: "7-777-777-77",
          // ----
          similarEnterprises: [],
          otherEnterprises: [],
          educationalEstablishments: [],
          professions: [],
          internshipsAndInternships: [],
          vacancy: [],
        },
        profession: {
          id: 1,
          type: "profession",
          name: "name profession",
          transliterationName: "transiteration_name_profession",
          icon: "/",
          startSalary: 50_000,
          endSalary: 250_000,
          averageSalary: 150_000,
          salaryCurrency: "rub",
          previewDesc: "previewDesc profession",
          description: "desc profession", // редактор
          photos: [""],
          previewPhoto: "/",
          subcategories: [], // IProfession[]
          knowledge: [""], // можно вставить редактор описние или массив строк
          tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
          DateOfBirth: new Date(),
          // ----
          similarProfessions: [],
          otherProfessions: [],
          educationalEstablishments: [],
          enterprises: [],
          internshipsAndInternships: [],
          vacancy: [],
        },
        icon: "/",
        startSalary: 50_000,
        endSalary: 250_000,
        salaryPeriod: "hour",
        salaryCurrency: "rub",
        previewDesc: "desc preview internshipsAndPractices",
        photos: [""],
        previewPhoto: "/",
        description: "desc internshipsAndPractices", // редактор
        fullNameLocation: "yaroslavl",
        location: [1, 2],
        knowledge: [""], // можно вставить редактор описние или массив строк
        tags: [{ name: "Fulltime" }, { name: "Hybrid" }, { name: "2-4 Years" }],
        createdAt: new Date(),
        contacts: [{ name: "Vladimir", contact: "Zenovsky" }],
        city: "Yaroslavl",
        sizeInternshipsOrPractice: [10],
        specialization: "specialization internshipsAndPractices",
        staff: [
          {
            id: 1,
            photo: "/",
            name: "Иван",
            surname: "Абрамович",
            middleName: "Юрьевич",
            position: "Основатель СЕВЕРМАШ",
            contact: { name: "Иван Юрьевич", contact: "7-777-777-777" },
          },
        ],
        advantagesOfTheEntity: [{ icon: "icon", text: "Льготы по здоровью" }],
        phone: "7-777-777-77",
        // ----
        similarInternshipsAndPractices: [],
        otherInternshipsAndPractices: [],
        educationalEstablishments: [],
        enterprises: [],
        professions: [],
        vacancy: [],
      },
    ],
    educationalEstablishments: [],
    enterprises: [],
    professions: [],
    vacancy: [],
  },
];
